In [5]:
import numpy as np
import scipy.fftpack as fp

import scipy.linalg  as lg

In [9]:
x= np.array([1,0,0,0,0,0,0,0])
X= fp.fft(x)
xx= fp.ifft(X)
X

array([1.-0.j, 1.+0.j, 1.-0.j, 1.+0.j, 1.-0.j, 1.-0.j, 1.+0.j, 1.-0.j])

In [8]:
x= np.array([1,1,1,1,1,1,1,1])
X= fp.fft(x)
X

array([8.-0.j, 0.+0.j, 0.-0.j, 0.+0.j, 0.-0.j, 0.-0.j, 0.+0.j, 0.-0.j])

In [10]:
x= np.array([1,-1,1,-1,1,-1,1,-1])
X= fp.fft(x)
X

array([0.-0.j, 0.+0.j, 0.-0.j, 0.+0.j, 8.-0.j, 0.-0.j, 0.+0.j, 0.-0.j])

In [11]:
x= np.array([3,0,2,0,2,0,2,0])
X= fp.fft(x)
X

array([9.-0.j, 1.+0.j, 1.-0.j, 1.+0.j, 9.-0.j, 1.-0.j, 1.+0.j, 1.-0.j])

In [12]:
x= np.array([1,1,0,0,0,0,1,1])
X= fp.ifft(x)
X

array([ 0.5      -0.j   ,  0.3017767-0.125j,  0.       +0.j   ,
       -0.0517767+0.125j,  0.       -0.j   , -0.0517767-0.125j,
        0.       -0.j   ,  0.3017767+0.125j])

In [25]:

a = [1,0,0,0,0,0,0,0]
b = [1,1,1,1,1,1,1,1]
c = [1,-1,1,-1,1,-1,1,-1]
d = [3,0,2,0,2,0,2,0]

dft_a = fp.dct(a)
dft_b = fp.dct(b)
dft_c = fp.dct(c)
dft_d = fp.dct(d)

f1 = [1,1,0,0,0,0,1,1]
f2 = [1,1,0,0,0,0,0,1]

idft_f1 = fp.idct(f1)
idft_f2 = fp.idct(f2)

g1 = [1,1,0,0]
g2 = [1,1,0,0,0,0,0,0]

dft_g1=fp.dct(g1)
dft_g2=fp.dct(g2)

In [14]:
dft_a

array([2.        , 1.96157056, 1.84775907, 1.66293922, 1.41421356,
       1.11114047, 0.76536686, 0.39018064])

In [15]:
dft_b

array([16.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [16]:
dft_c

array([ 0.        ,  2.03918232,  0.        ,  2.40537955,  0.        ,
        3.59990489,  0.        , 10.25166179])

In [17]:
dft_d

array([18.        ,  4.00075288,  1.84775907,  4.06831877,  1.41421356,
        4.71104536,  0.76536686, 10.64184243])

In [22]:
idft_f1

array([ 4.11711807, -0.29596031,  5.62183876, -1.33675678,  1.80602305,
        0.07367937, -1.39955782, -0.58638434])

In [23]:
idft_f2

array([ 3.3517512 ,  1.55179876,  3.77407969, -0.57138992,  2.57138992,
       -1.77407969,  0.44820124, -1.3517512 ])

In [26]:
dft_g1

array([ 4.        ,  2.61312593,  0.        , -1.0823922 ])

In [27]:
dft_g2

array([ 4.        ,  3.62450979,  2.61312593,  1.27275858,  0.        ,
       -0.85043009, -1.0823922 , -0.72095982])

In [ ]:
1.

In [ ]:
(a)
array([2.        , 1.96157056, 1.84775907, 1.66293922, 1.41421356,
       1.11114047, 0.76536686, 0.39018064])

In [ ]:
(b)
array([16.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
(c)
array([ 0.        ,  2.03918232,  0.        ,  2.40537955,  0.        ,
        3.59990489,  0.        , 10.25166179])

In [ ]:
(d)
array([18.        ,  4.00075288,  1.84775907,  4.06831877,  1.41421356,
        4.71104536,  0.76536686, 10.64184243])

In [ ]:
(e)
倒數

In [ ]:
(f)
f1=array([ 4.11711807, -0.29596031,  5.62183876, -1.33675678,  1.80602305,
        0.07367937, -1.39955782, -0.58638434])
f2=array([ 3.3517512 ,  1.55179876,  3.77407969, -0.57138992,  2.57138992,
       -1.77407969,  0.44820124, -1.3517512 ])
都不是實數

In [ ]:
(g)
g1=array([ 4.        ,  2.61312593,  0.        , -1.0823922 ])
g2=array([ 4.        ,  3.62450979,  2.61312593,  1.27275858,  0.        ,
       -0.85043009, -1.0823922 , -0.72095982])
g2較g1多出 3.6245 , 1.2727 ,-0.8504 ,-0.7209
因多出4個0導致

In [ ]:
3.

In [ ]:
(a)(b)為圖檔，在github內，存本檔案的下方 (出去就看得到了)